services:
  - type: web
    name: bank-backend
    env: node
    buildCommand: npm install && npx prisma generate && npx tsc
    startCommand: npx prisma db push --accept-data-loss && node dist/index.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres.logiumjyfecwcssjlpmz:numagyong01@aws-0-eu-west-1.pooler.supabase.com:5432/postgres
      - key: CORS_ORIGINS
        value: https://bank-app-ten-sigma.vercel.app
      - key: SENDGRID_FROM_EMAIL
        value: noreply@apexbank.com
      - key: SENDGRID_FROM_NAME
        value: APEX BANK
      - key: SUPPORT_PHONE
        value: '+1 (302) 290-6516'
      - key: SUPPORT_EMAIL
        value: support@apexbank.com
      - key: LOGO_URL
        value: https://apexbank.com/logo.png
