services:
  - type: web
    name: bank-backend
    env: node
    buildCommand: npm install && npx prisma generate && npx tsc
    startCommand: npx prisma db push --accept-data-loss && node dist/index.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres.logiumjyfecwcssjlpmz:numagyong01@aws-0-eu-west-1.pooler.supabase.com:6543/postgres?pgbouncer=true&connection_limit=5
      - key: DIRECT_URL
        value: postgresql://postgres.logiumjyfecwcssjlpmz:numagyong01@aws-0-eu-west-1.pooler.supabase.com:5432/postgres
      - key: CORS_ORIGINS
        value: https://bank-app-ten-sigma.vercel.app
      - key: BREVO_API_KEY
        value: YOUR_BREVO_API_KEY_HERE
      - key: BREVO_FROM_EMAIL
        value: apexbanksupports@gmail.com
      - key: BREVO_SENDER_NAME
        value: NOVA CREDIT UNION
      - key: SUPPORT_PHONE
        value: '+1 (302) 290-6516'
      - key: SUPPORT_EMAIL
        value: support@novacu.com
      - key: LOGO_URL
        value: https://novacu.com/logo.png
