const EXCHANGE_RATES: Record<string, number> = {
  USD: 1.0,
  EUR: 0.92,
  GBP: 0.79,
  JPY: 149.5,
  CAD: 1.36,
  AUD: 1.53,
  CHF: 0.88,
  CNY: 7.24,
  MXN: 17.15,
  BRL: 4.97,
  ARS: 350.0,
  CLP: 880.0,
  COP: 3950.0,
  PEN: 3.72,
  GTQ: 7.82,
  HNL: 24.65,
  SVC: 8.75,
  NIO: 36.65,
  CRC: 520.0,
  PAB: 1.0,
  DOP: 56.5,
  JMD: 155.0,
  TTD: 6.78,
  BSD: 1.0,
  BBD: 2.0,
  HTG: 135.0,
  BZD: 2.0,
  CUP: 24.0,
  NAD: 18.5,
  ZAR: 18.5,
  NGN: 780.0,
  KES: 153.0,
  GHS: 12.5,
  EGP: 30.9,
  MAD: 10.1,
  TND: 3.1,
  DZD: 135.0,
  PKR: 285.0,
  INR: 83.2,
  BDT: 110.0,
  LKR: 310.0,
  NPR: 133.5,
  THB: 35.5,
  VND: 24500.0,
  IDR: 15450.0,
  MYR: 4.72,
  PHP: 56.5,
  SGD: 1.34,
  KRW: 1320.0,
  TWD: 31.5,
  HKD: 7.82,
  NZD: 1.64,
  ILS: 3.67,
  SAR: 3.75,
  AED: 3.67,
  QAR: 3.64,
  KWD: 0.31,
  BHD: 0.38,
  OMR: 0.39,
  JOD: 0.71,
  IQD: 1310.0,
  RUB: 92.0,
  TRY: 28.5,
  PLN: 4.02,
  CZK: 22.5,
  HUF: 355.0,
  RON: 4.57,
  BGN: 1.80,
  HRK: 6.93,
  SEK: 10.45,
  NOK: 10.65,
  DKK: 6.87,
  ISK: 137.0,
  UAH: 37.5,
  RSD: 92.0,
  ALL: 93.0,
  MKD: 57.0,
  BAM: 1.80,
  MZN: 63.5,
  SZL: 18.5,
  LSL: 18.5,
  BWP: 13.5,
  MWK: 1035.0,
  ZMW: 20.5,
  BIF: 2850.0,
  SOS: 565.0,
  SDG: 600.0,
  SLL: 20900.0,
  LRD: 155.0,
  GNF: 8600.0,
  TJS: 10.9,
  KZT: 460.0,
  UZS: 12200.0,
  KGS: 89.0,
  TMT: 3.5,
  AMD: 390.0,
  GEL: 2.7,
  AZN: 1.7,
  MDL: 17.8,
  BYN: 3.2,
  BND: 1.34,
};

export function getExchangeRate(from: string, to: string): number {
  const fromRate = EXCHANGE_RATES[from] || 1;
  const toRate = EXCHANGE_RATES[to] || 1;
  return toRate / fromRate;
}

export function convertCurrency(amount: number, from: string, to: string): number {
  if (from === to) return amount;
  const rate = getExchangeRate(from, to);
  return Math.round(amount * rate * 100) / 100;
}

export function getSupportedCurrencies(): { code: string; name: string; rate: number }[] {
  return [
    { code: 'USD', name: 'US Dollar', rate: 1 },
    { code: 'EUR', name: 'Euro', rate: EXCHANGE_RATES.EUR },
    { code: 'GBP', name: 'British Pound', rate: EXCHANGE_RATES.GBP },
    { code: 'JPY', name: 'Japanese Yen', rate: EXCHANGE_RATES.JPY },
    { code: 'CAD', name: 'Canadian Dollar', rate: EXCHANGE_RATES.CAD },
    { code: 'AUD', name: 'Australian Dollar', rate: EXCHANGE_RATES.AUD },
    { code: 'CHF', name: 'Swiss Franc', rate: EXCHANGE_RATES.CHF },
    { code: 'CNY', name: 'Chinese Yuan', rate: EXCHANGE_RATES.CNY },
    { code: 'MXN', name: 'Mexican Peso', rate: EXCHANGE_RATES.MXN },
    { code: 'BRL', name: 'Brazilian Real', rate: EXCHANGE_RATES.BRL },
    { code: 'ARS', name: 'Argentine Peso', rate: EXCHANGE_RATES.ARS },
    { code: 'CLP', name: 'Chilean Peso', rate: EXCHANGE_RATES.CLP },
    { code: 'COP', name: 'Colombian Peso', rate: EXCHANGE_RATES.COP },
    { code: 'PEN', name: 'Peruvian Sol', rate: EXCHANGE_RATES.PEN },
    { code: 'INR', name: 'Indian Rupee', rate: EXCHANGE_RATES.INR },
    { code: 'SGD', name: 'Singapore Dollar', rate: EXCHANGE_RATES.SGD },
    { code: 'HKD', name: 'Hong Kong Dollar', rate: EXCHANGE_RATES.HKD },
    { code: 'KRW', name: 'South Korean Won', rate: EXCHANGE_RATES.KRW },
    { code: 'THB', name: 'Thai Baht', rate: EXCHANGE_RATES.THB },
    { code: 'PHP', name: 'Philippine Peso', rate: EXCHANGE_RATES.PHP },
    { code: 'MYR', name: 'Malaysian Ringgit', rate: EXCHANGE_RATES.MYR },
    { code: 'IDR', name: 'Indonesian Rupiah', rate: EXCHANGE_RATES.IDR },
    { code: 'VND', name: 'Vietnamese Dong', rate: EXCHANGE_RATES.VND },
    { code: 'NZD', name: 'New Zealand Dollar', rate: EXCHANGE_RATES.NZD },
    { code: 'SEK', name: 'Swedish Krona', rate: EXCHANGE_RATES.SEK },
    { code: 'NOK', name: 'Norwegian Krone', rate: EXCHANGE_RATES.NOK },
    { code: 'DKK', name: 'Danish Krone', rate: EXCHANGE_RATES.DKK },
    { code: 'PLN', name: 'Polish Zloty', rate: EXCHANGE_RATES.PLN },
    { code: 'CZK', name: 'Czech Koruna', rate: EXCHANGE_RATES.CZK },
    { code: 'HUF', name: 'Hungarian Forint', rate: EXCHANGE_RATES.HUF },
    { code: 'TRY', name: 'Turkish Lira', rate: EXCHANGE_RATES.TRY },
    { code: 'RUB', name: 'Russian Ruble', rate: EXCHANGE_RATES.RUB },
    { code: 'ZAR', name: 'South African Rand', rate: EXCHANGE_RATES.ZAR },
    { code: 'NGN', name: 'Nigerian Naira', rate: EXCHANGE_RATES.NGN },
    { code: 'EGP', name: 'Egyptian Pound', rate: EXCHANGE_RATES.EGP },
    { code: 'AED', name: 'UAE Dirham', rate: EXCHANGE_RATES.AED },
    { code: 'SAR', name: 'Saudi Riyal', rate: EXCHANGE_RATES.SAR },
    { code: 'PKR', name: 'Pakistani Rupee', rate: EXCHANGE_RATES.PKR },
    { code: 'BDT', name: 'Bangladeshi Taka', rate: EXCHANGE_RATES.BDT },
    { code: 'KES', name: 'Kenyan Shilling', rate: EXCHANGE_RATES.KES },
    { code: 'GHS', name: 'Ghanaian Cedi', rate: EXCHANGE_RATES.GHS },
  ];
}
